services:
  kafka-primary:
    image: apache/kafka:4.0.0
    platform: linux/arm64  # Mac M1 ready; remove if on amd64
    container_name: kafka-primary
    hostname: kafka-primary
    ports:
      - "19092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-primary:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-primary:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks: [mm2net]

  kafka-dr:
    image: apache/kafka:4.0.0
    platform: linux/arm64
    container_name: kafka-dr
    hostname: kafka-dr
    ports:
      - "29092:9092"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-dr:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 2@kafka-dr:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks: [mm2net]

  # Vanilla MM2 to prove baseline replication
  mm2-vanilla:
    image: apache/kafka:4.0.0
    platform: linux/arm64
    container_name: mm2-vanilla
    hostname: mm2-vanilla
    depends_on: [kafka-primary, kafka-dr]
    environment:
      # Connect worker runs against the TARGET (DR) cluster
      KAFKA_OPTS: ""
    command: ["bash", "-c", "/opt/kafka/bin/connect-mirror-maker.sh /opt/kafka/mm2/connect-mirror-maker.vanilla.properties"]
    volumes:
      - ./mm2/connect-mirror-maker.vanilla.properties:/opt/kafka/mm2/connect-mirror-maker.vanilla.properties
    networks: [mm2net]

  # Enhanced MM2 (built from Kafka 4.0.0 source with our patch)
  mm2-enhanced:
    build:
      context: ./mm2
      dockerfile: Dockerfile.enhanced-mm2
      args:
        KAFKA_VERSION: "4.0.0"
    platform: linux/arm64
    container_name: mm2-enhanced
    hostname: mm2-enhanced
    depends_on: [kafka-primary, kafka-dr]
    command: ["/opt/mm2/entrypoint-enhanced.sh"]
    volumes:
      - ./mm2/connect-mirror-maker.enhanced.properties:/opt/mm2/connect-mirror-maker.enhanced.properties
    networks: [mm2net]

  producer:
    build: ./producer
    platform: linux/arm64
    container_name: commitlog-producer
    depends_on: [kafka-primary]
    networks: [mm2net]

  verifier:
    build:
      context: ./verify
      dockerfile: Dockerfile
    platform: linux/arm64
    container_name: verifier
    working_dir: /app
    command: ["python", "verify_replication.py"]
    depends_on: [kafka-dr]
    networks: [mm2net]

networks:
  mm2net:
    name: mm2net
